# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12FGvk0Ou0-Yg40DolRnEpDUwZqB_ajKo
"""

individuos = []

def  grabar_individuos():
    nif = input("Ingrese el NIF: ")
    nombre = input("Ingrese el Nombre: ")
    edad = int(input("Ingrese la Edad: "))

    if len(nif) < 8:
        print("Error: NIF invalido. ")

    if edad < 8:
      print("Error: Edad invalida. ")

    individuo = [nif, nombre, edad]
    individuos.append(individuo)
    print("Individuo registradO correctamente.")

    individuo = {
        "NIF": nif,
        "Nombre": nombre,
        "Edad": edad,
    }
    individuos.append(individuo)
    print("Datos del individuo grabados exitosamente.")

def buscar_individuo():
    nif = input("Ingrese el NIF del individuo a buscar: ")
    encontrado = False

    for individuo in individuos:
        if individuos["NIF"] == nif:
            print("Información del individuo:")
            print("Nombre:", individuo["Nombre"])
            print("Edad:", individuo["Edad"])
            encontrado = True
            break

def certificado():
    print("Certificado Nacimiento, Estado Conyugal, Pertenencia Union Europea")
    certificado = input("Ingrese el certificado requerido: ")
    nif = input("Ingrese el NIF del individuo")
    nombre = input("Ingrese el nombre del individuo: ")
    edad = input("Ingrese la edad de la persona: ")

    return (certificado), nif, nombre, edad

def imprimir_certificados(certificado, nif, nombre, edad):
    print("")
    print("Certificado:", certificado)
    print("NIF:", nif)
    print("Nombre del individuo:", nombre)
    print("Edad del individuo:", edad)
    print("")

def main():
    print("Bienvenido al Registro Civil Europeo")

    while True:
        print("====MENU====")
        print("1. Grabar individuo")
        print("2. Buscar individuo")
        print("3. Imprimir certificados")
        print("4. Salir")

        opcion = input("Ingrese el numero de opcion:" )

        if opcion == "1":
            grabar_individuos()
        elif opcion == "2":
            buscar_individuo()
        elif opcion == "3":
            certificado_info = certificado()
            imprimir_certificados(*certificado_info)
        elif opcion == "4":
            print("Gracias por usar el programa.")
            break
        else:
            print("Opcion invalida. Intente nuevamente. ")

if __name__ == "__main__":
    main()